# Generated by Django 5.0.4 on 2024-04-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='editedOn',
        ),
        migrations.RemoveField(
            model_name='post',
            name='editedOn',
        ),
        migrations.AddField(
            model_name='comment',
            name='editedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='postDate',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='editedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
