# Generated by Django 5.0.4 on 2024-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0002_remove_userprofile_votes_userprofile_commentvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
