# Generated by Django 5.0.4 on 2024-04-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0003_userprofile_isdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(-1, 'dislike'), (0, ''), (1, 'like')], default=0)),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogApi.comment')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogApi.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApi.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commentVotes',
            field=models.ManyToManyField(related_name='commentVotes', through='blogApi.Vote', to='blogApi.comment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postVotes',
            field=models.ManyToManyField(related_name='postVotes', through='blogApi.Vote', to='blogApi.post'),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
