# Generated by Django 5.0.4 on 2024-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0003_remove_comment_post_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
