# Generated by Django 5.0.4 on 2024-04-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0004_vote_alter_userprofile_commentvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='commentVotes',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
    ]
