# Generated by Django 5.0.4 on 2024-04-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0005_remove_userprofile_commentvotes_remove_vote_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(-1, 'dislike'), (0, 'None'), (1, 'like')], default=0)),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogApi.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApi.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commentVotes',
            field=models.ManyToManyField(related_name='commentVotes', through='blogApi.CommentVote', to='blogApi.comment'),
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(-1, 'dislike'), (0, 'None'), (1, 'like')], default=0)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogApi.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApi.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postVotes',
            field=models.ManyToManyField(related_name='postVotes', through='blogApi.PostVote', to='blogApi.post'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
