# Generated by Django 5.0.4 on 2024-04-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0005_remove_comment_post_id_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commentDislikes',
            field=models.ManyToManyField(blank=True, related_name='commentDislikes', to='blogApi.comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commentLikes',
            field=models.ManyToManyField(blank=True, related_name='commentLikes', to='blogApi.comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postDislikes',
            field=models.ManyToManyField(blank=True, related_name='postDislikes', to='blogApi.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postLikes',
            field=models.ManyToManyField(blank=True, related_name='postLikes', to='blogApi.post'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
