# Generated by Django 5.0.4 on 2024-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0007_remove_userprofile_followers_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='commentDislikes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='commentLikes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postDislikes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commentVotes',
            field=models.ManyToManyField(default=0, limit_choices_to={-1, 0, 1}, related_name='commentVotes', to='blogApi.comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postVotes',
            field=models.ManyToManyField(default=0, limit_choices_to={-1, 0, 1}, related_name='postVotes', to='blogApi.post'),
        ),
    ]
