# Generated by Django 5.0.4 on 2024-04-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0008_remove_userprofile_commentdislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='postLikes',
        ),
    ]
