# Generated by Django 5.0.4 on 2024-04-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0010_alter_userprofile_following_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
    ]
