# Generated by Django 5.0.4 on 2024-04-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0011_remove_userprofile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='commentVotes',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='comment',
        ),
    ]
