# Generated by Django 5.0.4 on 2024-04-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0012_remove_userprofile_commentvotes_remove_votes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='postVotes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Votes',
            field=models.ManyToManyField(related_name='Votes', through='blogApi.Votes', to='blogApi.post'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blogApi.post'),
        ),
    ]
